version: '3.3'

services:
  treinadb:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: treinapwdrood
      MYSQL_DATABASE: treinapass
      MYSQL_USER: treinauser
      MYSQL_PASSWORD: treinapwd
    
  treinapass:
    depends_on:
      - treinadb
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: treinadb:3306
      WORDPRESS_DB_USER: treinauser
      WORDPRESS_DB_PASSWORD: treinapwd
      WORDPRESS_DB_NAME: treinapass

volumes:
  db_data: {}
